name: env
channels:
- defaults
- conda-forge
- cantera
dependencies:
  - python>=3.10
  - numpy>=1.13.1
  - cantera>=3.0.1
  - networkx
  - blosc=1.20.0
  - pytables
  - ruamel_yaml
  - pytest>=3.2.0
  - pytest-cov>=2.3.1
  - codecov
